"""Localized user-interface copy for Ask Dashboard.

Canonical question values and feedback codes remain stable in English/internal form.
This module changes display copy only; routing, calculations, and analytics contracts
continue to receive the existing canonical values.
"""

from ask_dashboard import (
    QUESTION_CUSTOM,
    QUESTION_EXCLUSION_IMPACT,
    QUESTION_HELP,
    QUESTION_NEGATIVE_PERCENTAGE,
    QUESTION_NET_VS_POSITIVE,
    QUESTION_TOP_CONTRIBUTOR,
    QUESTION_TOP_CONTRIBUTORS,
)


SUPPORTED_UI_LOCALES = ("en", "es", "fr", "vi", "id")


ASK_UI_TEXT = {
    "en": {
        "ask_dashboard": "Ask the Dashboard",
        "current_scope": "Current scope — SVS: {svs} | Alliances: {alliances} | Net status: {net_status} | Included players: {included}/{total}",
        "none": "None",
        "analytics_privacy": "Preview analytics & privacy",
        "analytics_local": "Anonymous routing metadata and feedback are saved to a best-effort local file on this running preview instance. It can persist across browser sessions, but may reset when Streamlit restarts or redeploys.",
        "analytics_webhook": "Anonymous routing metadata and feedback are sent to the configured HTTPS analytics endpoint.",
        "analytics_disabled": "Persistent preview analytics are currently disabled.",
        "analytics_opt_in": "A custom question and its generated answer are saved only when you explicitly opt in. The analytics event does not collect IP addresses, browser fingerprints, API keys, score rows, or selected player names.",
        "choose_suggested_question": "Choose a suggested question",
        "custom_question_notice": "Free-text questions and generated explanations currently work in English. You can still use the dashboard interface in your selected language.",
        "custom_question_help": "Type “help” for usage guidance, or ask directly about alliance rankings, player exclusions, negative share, top contributors, or net score.",
        "enter_question": "Enter your question",
        "question_placeholder": "Try: Top net score player — or type help",
        "allow_save_text": "Allow this custom question and its generated answer to be saved for improving Ask Dashboard",
        "allow_save_help": "When unchecked, only anonymous routing metadata is saved. Avoid entering private information even when opting in.",
        "explain": "Explain",
        "explanation": "Explanation",
        "feedback_pending": "Feedback is temporarily unavailable because analytics delivery for this answer has not been confirmed.",
        "retry_analytics": "Retry analytics connection",
        "retry_failed": "Analytics delivery still could not be confirmed. The answer remains available, and retrying the same event is safe.",
        "feedback_recorded": "Thank you — your feedback was recorded.",
        "was_helpful": "Was this answer helpful?",
        "choose": "Choose…",
        "helpful": "Helpful",
        "not_helpful": "Not helpful",
        "what_went_wrong": "What went wrong?",
        "reason_misunderstood": "It misunderstood my question",
        "reason_incorrect": "The answer was incorrect",
        "reason_unsupported": "My question is not supported",
        "reason_unclear": "The answer was unclear",
        "reason_other": "Other",
        "optional_comment": "Optional comment",
        "comment_placeholder": "Tell us what worked or what you expected. Do not include private information.",
        "submit_feedback": "Submit feedback",
        "feedback_delivery_failed": "Feedback delivery could not be confirmed. You can retry safely; retries for the same answer will not create another feedback record.",
        "suggest_net_vs_positive": "Why does the top net-score alliance rank second in positive contribution?",
        "suggest_exclusion": "What changed after excluding the selected players?",
        "suggest_negative_share": "Why did the negative percentage increase?",
        "suggest_top_contributor": "Who contributed the most under the current filters?",
        "suggest_top_contributors": "Show the top contributors within each selected alliance.",
        "suggest_help": "Help — learn how to use Ask Dashboard",
        "suggest_custom": "Write my own question",
    },
    "es": {
        "ask_dashboard": "Preguntar al panel",
        "current_scope": "Ámbito actual — SVS: {svs} | Alianzas: {alliances} | Estado neto: {net_status} | Jugadores incluidos: {included}/{total}",
        "none": "Ninguno",
        "analytics_privacy": "Analítica de vista previa y privacidad",
        "analytics_local": "Los metadatos anónimos de enrutamiento y los comentarios se guardan, en la medida de lo posible, en un archivo local de esta instancia de vista previa. Pueden persistir entre sesiones del navegador, pero podrían restablecerse cuando Streamlit se reinicie o se vuelva a desplegar.",
        "analytics_webhook": "Los metadatos anónimos de enrutamiento y los comentarios se envían al endpoint HTTPS de analítica configurado.",
        "analytics_disabled": "La analítica persistente de la vista previa está desactivada actualmente.",
        "analytics_opt_in": "Una pregunta personalizada y su respuesta generada solo se guardan si lo autorizas expresamente. El evento de analítica no recopila direcciones IP, huellas del navegador, claves de API, filas de puntuaciones ni nombres de jugadores seleccionados.",
        "choose_suggested_question": "Elige una pregunta sugerida",
        "custom_question_notice": "Las preguntas de texto libre y las explicaciones generadas funcionan actualmente en inglés. Puedes seguir usando la interfaz del panel en el idioma seleccionado.",
        "custom_question_help": "Escribe “help” para ver la guía de uso o pregunta directamente sobre clasificaciones de alianzas, exclusión de jugadores, participación negativa, principales contribuyentes o puntuación neta.",
        "enter_question": "Escribe tu pregunta",
        "question_placeholder": "Prueba: Top net score player — o escribe help",
        "allow_save_text": "Permitir guardar esta pregunta personalizada y su respuesta para mejorar Ask Dashboard",
        "allow_save_help": "Si no marcas esta opción, solo se guardarán metadatos anónimos de enrutamiento. Evita introducir información privada incluso si autorizas el guardado.",
        "explain": "Explicar",
        "explanation": "Explicación",
        "feedback_pending": "Los comentarios no están disponibles temporalmente porque no se ha confirmado la entrega de la analítica de esta respuesta.",
        "retry_analytics": "Reintentar conexión de analítica",
        "retry_failed": "No se pudo confirmar la entrega de la analítica. La respuesta sigue disponible y es seguro reintentar el mismo evento.",
        "feedback_recorded": "Gracias — tus comentarios se registraron.",
        "was_helpful": "¿Te resultó útil esta respuesta?",
        "choose": "Elegir…",
        "helpful": "Útil",
        "not_helpful": "No útil",
        "what_went_wrong": "¿Qué salió mal?",
        "reason_misunderstood": "No entendió mi pregunta",
        "reason_incorrect": "La respuesta era incorrecta",
        "reason_unsupported": "Mi pregunta no está admitida",
        "reason_unclear": "La respuesta no era clara",
        "reason_other": "Otro",
        "optional_comment": "Comentario opcional",
        "comment_placeholder": "Cuéntanos qué funcionó o qué esperabas. No incluyas información privada.",
        "submit_feedback": "Enviar comentarios",
        "feedback_delivery_failed": "No se pudo confirmar la entrega de los comentarios. Puedes reintentarlo de forma segura; los reintentos para la misma respuesta no crearán otro registro.",
        "suggest_net_vs_positive": "¿Por qué la alianza con mayor puntuación neta ocupa el segundo lugar en contribución positiva?",
        "suggest_exclusion": "¿Qué cambió después de excluir a los jugadores seleccionados?",
        "suggest_negative_share": "¿Por qué aumentó el porcentaje negativo?",
        "suggest_top_contributor": "¿Quién contribuyó más con los filtros actuales?",
        "suggest_top_contributors": "Mostrar los principales contribuyentes de cada alianza seleccionada.",
        "suggest_help": "Ayuda — aprender a usar Ask Dashboard",
        "suggest_custom": "Escribir mi propia pregunta",
    },
    "fr": {
        "ask_dashboard": "Interroger le tableau de bord",
        "current_scope": "Périmètre actuel — SVS : {svs} | Alliances : {alliances} | Statut net : {net_status} | Joueurs inclus : {included}/{total}",
        "none": "Aucun",
        "analytics_privacy": "Analytique de prévisualisation et confidentialité",
        "analytics_local": "Les métadonnées anonymes de routage et les retours sont enregistrés, dans la mesure du possible, dans un fichier local de cette instance de prévisualisation. Ils peuvent persister entre les sessions du navigateur, mais peuvent être réinitialisés lors d’un redémarrage ou d’un redéploiement de Streamlit.",
        "analytics_webhook": "Les métadonnées anonymes de routage et les retours sont envoyés au point de terminaison HTTPS d’analytique configuré.",
        "analytics_disabled": "L’analytique persistante de prévisualisation est actuellement désactivée.",
        "analytics_opt_in": "Une question personnalisée et la réponse générée ne sont enregistrées que si vous l’autorisez explicitement. L’événement d’analytique ne collecte ni adresse IP, ni empreinte de navigateur, ni clé API, ni ligne de scores, ni nom de joueur sélectionné.",
        "choose_suggested_question": "Choisissez une question suggérée",
        "custom_question_notice": "Les questions en texte libre et les explications générées fonctionnent actuellement en anglais. Vous pouvez continuer à utiliser l’interface du tableau de bord dans la langue sélectionnée.",
        "custom_question_help": "Saisissez “help” pour obtenir de l’aide, ou posez directement une question sur le classement des alliances, l’exclusion de joueurs, la part négative, les principaux contributeurs ou le score net.",
        "enter_question": "Saisissez votre question",
        "question_placeholder": "Essayez : Top net score player — ou saisissez help",
        "allow_save_text": "Autoriser l’enregistrement de cette question personnalisée et de sa réponse afin d’améliorer Ask Dashboard",
        "allow_save_help": "Si cette option n’est pas cochée, seules des métadonnées anonymes de routage sont enregistrées. Évitez de saisir des informations privées même si vous acceptez l’enregistrement.",
        "explain": "Expliquer",
        "explanation": "Explication",
        "feedback_pending": "Les retours sont temporairement indisponibles car la livraison des données analytiques de cette réponse n’a pas été confirmée.",
        "retry_analytics": "Réessayer la connexion analytique",
        "retry_failed": "La livraison des données analytiques n’a toujours pas pu être confirmée. La réponse reste disponible et il est sûr de réessayer le même événement.",
        "feedback_recorded": "Merci — votre retour a été enregistré.",
        "was_helpful": "Cette réponse vous a-t-elle été utile ?",
        "choose": "Choisir…",
        "helpful": "Utile",
        "not_helpful": "Pas utile",
        "what_went_wrong": "Quel était le problème ?",
        "reason_misunderstood": "La question a été mal comprise",
        "reason_incorrect": "La réponse était incorrecte",
        "reason_unsupported": "Ma question n’est pas prise en charge",
        "reason_unclear": "La réponse manquait de clarté",
        "reason_other": "Autre",
        "optional_comment": "Commentaire facultatif",
        "comment_placeholder": "Dites-nous ce qui a fonctionné ou ce que vous attendiez. N’incluez pas d’informations privées.",
        "submit_feedback": "Envoyer le retour",
        "feedback_delivery_failed": "La livraison du retour n’a pas pu être confirmée. Vous pouvez réessayer sans risque ; les nouvelles tentatives pour la même réponse ne créeront pas d’autre enregistrement.",
        "suggest_net_vs_positive": "Pourquoi l’alliance ayant le meilleur score net est-elle deuxième en contribution positive ?",
        "suggest_exclusion": "Qu’est-ce qui a changé après l’exclusion des joueurs sélectionnés ?",
        "suggest_negative_share": "Pourquoi le pourcentage négatif a-t-il augmenté ?",
        "suggest_top_contributor": "Qui a le plus contribué avec les filtres actuels ?",
        "suggest_top_contributors": "Afficher les principaux contributeurs de chaque alliance sélectionnée.",
        "suggest_help": "Aide — apprendre à utiliser Ask Dashboard",
        "suggest_custom": "Écrire ma propre question",
    },
    "vi": {
        "ask_dashboard": "Hỏi bảng điều khiển",
        "current_scope": "Phạm vi hiện tại — SVS: {svs} | Liên minh: {alliances} | Trạng thái ròng: {net_status} | Người chơi được tính: {included}/{total}",
        "none": "Không có",
        "analytics_privacy": "Phân tích bản xem trước và quyền riêng tư",
        "analytics_local": "Siêu dữ liệu định tuyến ẩn danh và phản hồi được lưu vào tệp cục bộ theo cơ chế cố gắng tối đa trên phiên bản xem trước đang chạy này. Dữ liệu có thể tồn tại qua các phiên trình duyệt nhưng có thể bị đặt lại khi Streamlit khởi động lại hoặc triển khai lại.",
        "analytics_webhook": "Siêu dữ liệu định tuyến ẩn danh và phản hồi được gửi đến endpoint HTTPS phân tích đã cấu hình.",
        "analytics_disabled": "Phân tích lưu trữ lâu dài cho bản xem trước hiện đang tắt.",
        "analytics_opt_in": "Câu hỏi tùy chỉnh và câu trả lời được tạo chỉ được lưu khi bạn chủ động đồng ý. Sự kiện phân tích không thu thập địa chỉ IP, dấu vân tay trình duyệt, khóa API, các dòng dữ liệu điểm hoặc tên người chơi đã chọn.",
        "choose_suggested_question": "Chọn một câu hỏi gợi ý",
        "custom_question_notice": "Câu hỏi dạng văn bản tự do và phần giải thích được tạo hiện chỉ hoạt động bằng tiếng Anh. Bạn vẫn có thể dùng giao diện bảng điều khiển bằng ngôn ngữ đã chọn.",
        "custom_question_help": "Gõ “help” để xem hướng dẫn sử dụng, hoặc hỏi trực tiếp về xếp hạng liên minh, loại người chơi, tỷ lệ âm, người đóng góp hàng đầu hoặc điểm ròng.",
        "enter_question": "Nhập câu hỏi của bạn",
        "question_placeholder": "Thử: Top net score player — hoặc gõ help",
        "allow_save_text": "Cho phép lưu câu hỏi tùy chỉnh này và câu trả lời được tạo để cải thiện Ask Dashboard",
        "allow_save_help": "Nếu không chọn, chỉ siêu dữ liệu định tuyến ẩn danh được lưu. Tránh nhập thông tin riêng tư ngay cả khi bạn đồng ý lưu.",
        "explain": "Giải thích",
        "explanation": "Giải thích",
        "feedback_pending": "Phản hồi tạm thời không khả dụng vì chưa xác nhận được việc gửi dữ liệu phân tích cho câu trả lời này.",
        "retry_analytics": "Thử lại kết nối phân tích",
        "retry_failed": "Vẫn chưa thể xác nhận việc gửi dữ liệu phân tích. Câu trả lời vẫn khả dụng và việc thử lại cùng một sự kiện là an toàn.",
        "feedback_recorded": "Cảm ơn — phản hồi của bạn đã được ghi nhận.",
        "was_helpful": "Câu trả lời này có hữu ích không?",
        "choose": "Chọn…",
        "helpful": "Hữu ích",
        "not_helpful": "Không hữu ích",
        "what_went_wrong": "Có vấn đề gì?",
        "reason_misunderstood": "Hệ thống hiểu sai câu hỏi của tôi",
        "reason_incorrect": "Câu trả lời không chính xác",
        "reason_unsupported": "Câu hỏi của tôi chưa được hỗ trợ",
        "reason_unclear": "Câu trả lời chưa rõ ràng",
        "reason_other": "Khác",
        "optional_comment": "Nhận xét tùy chọn",
        "comment_placeholder": "Hãy cho chúng tôi biết điều gì hữu ích hoặc bạn mong đợi điều gì. Không nhập thông tin riêng tư.",
        "submit_feedback": "Gửi phản hồi",
        "feedback_delivery_failed": "Không thể xác nhận việc gửi phản hồi. Bạn có thể thử lại an toàn; việc thử lại cho cùng một câu trả lời sẽ không tạo thêm bản ghi phản hồi.",
        "suggest_net_vs_positive": "Vì sao liên minh có điểm ròng cao nhất lại xếp thứ hai về đóng góp tích cực?",
        "suggest_exclusion": "Điều gì thay đổi sau khi loại những người chơi đã chọn?",
        "suggest_negative_share": "Vì sao tỷ lệ âm tăng lên?",
        "suggest_top_contributor": "Ai đóng góp nhiều nhất trong phạm vi bộ lọc hiện tại?",
        "suggest_top_contributors": "Hiển thị những người đóng góp hàng đầu trong từng liên minh đã chọn.",
        "suggest_help": "Trợ giúp — cách sử dụng Ask Dashboard",
        "suggest_custom": "Viết câu hỏi của riêng tôi",
    },
    "id": {
        "ask_dashboard": "Tanya Dasbor",
        "current_scope": "Cakupan saat ini — SVS: {svs} | Aliansi: {alliances} | Status bersih: {net_status} | Pemain yang disertakan: {included}/{total}",
        "none": "Tidak ada",
        "analytics_privacy": "Analitik pratinjau & privasi",
        "analytics_local": "Metadata perutean anonim dan umpan balik disimpan sebisa mungkin ke file lokal pada instans pratinjau yang sedang berjalan ini. Data dapat bertahan antar-sesi browser, tetapi dapat direset ketika Streamlit dimulai ulang atau diterapkan ulang.",
        "analytics_webhook": "Metadata perutean anonim dan umpan balik dikirim ke endpoint analitik HTTPS yang dikonfigurasi.",
        "analytics_disabled": "Analitik pratinjau persisten saat ini dinonaktifkan.",
        "analytics_opt_in": "Pertanyaan khusus dan jawaban yang dihasilkan hanya disimpan jika Anda secara eksplisit menyetujuinya. Peristiwa analitik tidak mengumpulkan alamat IP, sidik jari browser, kunci API, baris skor, atau nama pemain yang dipilih.",
        "choose_suggested_question": "Pilih pertanyaan yang disarankan",
        "custom_question_notice": "Pertanyaan teks bebas dan penjelasan yang dihasilkan saat ini bekerja dalam bahasa Inggris. Anda tetap dapat menggunakan antarmuka dasbor dalam bahasa yang dipilih.",
        "custom_question_help": "Ketik “help” untuk panduan penggunaan, atau tanyakan langsung tentang peringkat aliansi, pengecualian pemain, persentase negatif, kontributor teratas, atau poin bersih.",
        "enter_question": "Masukkan pertanyaan Anda",
        "question_placeholder": "Coba: Top net score player — atau ketik help",
        "allow_save_text": "Izinkan pertanyaan khusus ini dan jawaban yang dihasilkan disimpan untuk meningkatkan Ask Dashboard",
        "allow_save_help": "Jika tidak dicentang, hanya metadata perutean anonim yang disimpan. Hindari memasukkan informasi pribadi meskipun Anda memilih untuk menyimpan.",
        "explain": "Jelaskan",
        "explanation": "Penjelasan",
        "feedback_pending": "Umpan balik sementara tidak tersedia karena pengiriman analitik untuk jawaban ini belum dikonfirmasi.",
        "retry_analytics": "Coba lagi koneksi analitik",
        "retry_failed": "Pengiriman analitik masih belum dapat dikonfirmasi. Jawaban tetap tersedia dan aman untuk mencoba kembali peristiwa yang sama.",
        "feedback_recorded": "Terima kasih — umpan balik Anda telah dicatat.",
        "was_helpful": "Apakah jawaban ini membantu?",
        "choose": "Pilih…",
        "helpful": "Membantu",
        "not_helpful": "Tidak membantu",
        "what_went_wrong": "Apa yang salah?",
        "reason_misunderstood": "Pertanyaan saya disalahpahami",
        "reason_incorrect": "Jawabannya tidak benar",
        "reason_unsupported": "Pertanyaan saya belum didukung",
        "reason_unclear": "Jawabannya tidak jelas",
        "reason_other": "Lainnya",
        "optional_comment": "Komentar opsional",
        "comment_placeholder": "Beri tahu kami apa yang berhasil atau apa yang Anda harapkan. Jangan sertakan informasi pribadi.",
        "submit_feedback": "Kirim umpan balik",
        "feedback_delivery_failed": "Pengiriman umpan balik tidak dapat dikonfirmasi. Anda dapat mencoba lagi dengan aman; percobaan ulang untuk jawaban yang sama tidak akan membuat catatan umpan balik baru.",
        "suggest_net_vs_positive": "Mengapa aliansi dengan poin bersih tertinggi berada di peringkat kedua untuk kontribusi positif?",
        "suggest_exclusion": "Apa yang berubah setelah mengecualikan pemain yang dipilih?",
        "suggest_negative_share": "Mengapa persentase negatif meningkat?",
        "suggest_top_contributor": "Siapa yang berkontribusi paling besar dalam filter saat ini?",
        "suggest_top_contributors": "Tampilkan kontributor teratas dalam setiap aliansi yang dipilih.",
        "suggest_help": "Bantuan — pelajari cara menggunakan Ask Dashboard",
        "suggest_custom": "Tulis pertanyaan saya sendiri",
    },
}


SUGGESTED_QUESTION_KEYS = {
    QUESTION_NET_VS_POSITIVE: "suggest_net_vs_positive",
    QUESTION_EXCLUSION_IMPACT: "suggest_exclusion",
    QUESTION_NEGATIVE_PERCENTAGE: "suggest_negative_share",
    QUESTION_TOP_CONTRIBUTOR: "suggest_top_contributor",
    QUESTION_TOP_CONTRIBUTORS: "suggest_top_contributors",
    QUESTION_HELP: "suggest_help",
    QUESTION_CUSTOM: "suggest_custom",
}


FEEDBACK_CHOICES = ("choose", "helpful", "not_helpful")
FEEDBACK_REASON_KEYS = (
    "reason_misunderstood",
    "reason_incorrect",
    "reason_unsupported",
    "reason_unclear",
    "reason_other",
)

FEEDBACK_REASON_CODES = {
    "reason_misunderstood": "misunderstood_question",
    "reason_incorrect": "wrong_answer",
    "reason_unsupported": "unsupported_question",
    "reason_unclear": "unclear_answer",
    "reason_other": "other",
}


def ui_text(locale, key, **values):
    """Return localized UI copy with English fallback and optional formatting."""
    locale_text = ASK_UI_TEXT.get(locale, ASK_UI_TEXT["en"])
    template = locale_text.get(key, ASK_UI_TEXT["en"].get(key, key))
    return template.format(**values) if values else template


def suggested_question_label(locale, canonical_question):
    """Localize a suggested-question label without changing its canonical value."""
    key = SUGGESTED_QUESTION_KEYS.get(canonical_question)
    return ui_text(locale, key) if key else canonical_question


def feedback_choice_label(locale, choice_key):
    return ui_text(locale, choice_key)


def feedback_reason_label(locale, reason_key):
    return ui_text(locale, reason_key)
